---
title: "ATUS Sequence Analysis - Master"
date: "`r format(Sys.time(), '%B %d %Y')`"
output:
  pdf_document:
    toc: true
    toc_depth: 2
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(warning = FALSE)
knitr::opts_knit$set(root.dir = normalizePath(".."))
```

```{r include=FALSE}
theme_custom <- function() {
  theme_minimal() +
    theme(
      text = element_text(family = "Helvetica"),
      panel.grid.minor.y = element_blank(),
      panel.grid.major.x = element_blank(),
      panel.grid.minor.x = element_blank(),
    )
}

# set wrapper around saving plots so size and type is consistent
save_plot <- function(name, plot = ggplot2::last_plot(), type = "png", height = 4, width = 6.5){
  # function saves ggplots with standardized sizes
  
  ggplot2::ggsave(
    filename = paste0('Analyses/Plots/', name, '.', type),
    plot = plot,
    device = type,
    height = height,
    width = width
  )
}

```

```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(pander)
library(dendextend)
library(NbClust)
library(stringdist)
options(mc.cores = parallel::detectCores())
set.seed(44)
theme_set(theme_custom())

atus <- read_tsv('Data/atus.tsv')
demographics <- read_tsv('Data/demographic.tsv')
demographics <- demographics %>% 
  mutate(has_child = as.numeric(n_child > 0)) %>% 
  select(-c('age_youngest', 'n_child', 'state'))
```


```{r}
# throw out IDs with at least one NA
atus <- atus %>% 
  group_by(ID) %>% 
  na.omit() %>% 
  ungroup()

# table matching description to letter
string_table <- distinct(atus, description) %>% 
  mutate(string = LETTERS[1:(nrow(.))])
```

```{r}
# turn each ID into a string
atus_string <- atus %>% 
  left_join(string_table) %>% 
  group_by(ID) %>% 
  summarize(string = paste0(string, collapse = ""))
```

```{r}
# sample (SHOULD SAMPLE USING WEIGHTS)
atus_string_samp <- sample_n(atus_string, size = 2500)
```

```{r}
# compute the string distances
dist_matrix <- stringdistmatrix(a = atus_string_samp$string, method = "osa")

# ward (D2) linkage hier clustering
hcl_ward <- hclust(d = dist_matrix, method = 'ward.D2')
# plot(hcl_ward)
```


```{r}
# convert cluster to dendrogram
dend <- as.dendrogram(hcl_ward)
dend <- cut(dend, h = 10)$upper # cut off bottom of dendogram for computation performance
ggd1 <- as.ggdend(dend)
```

```{r fig.height=3.7, fig.width=7}
# plot the dendrogram
ggplot(ggd1$segments) + 
  geom_segment(aes(x = x, y = y, xend = xend, yend = yend), color = 'grey50', lwd = 0.6, alpha = 0.7) +
  coord_cartesian(ylim = c(10, 700), clip = 'off') +
  scale_x_continuous(labels = NULL) +
  scale_y_continuous(labels = NULL) +
  labs(title = 'Hierarchical clustering',
       subtitle= 'Ward (D2) linkage',
       x = NULL,
       y = NULL) +
  theme(axis.ticks = element_blank(),
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        legend.position = 'none')
```








# code from cluster analysis

```{r}
theme_web_light <- theme(
    axis.title = element_text(color = "gray30"),
  axis.ticks = element_line(color = NA),
  plot.title = element_text(color = "gray30",
                            face = "bold"),
  plot.subtitle = element_text(size = 10,
                               color = "gray30"),
  text = element_text(family = "Helvetica"),
  plot.caption = element_text(face = "italic",
                              size = 6,
                              color = 'grey50')
)

theme_web <- theme(
  plot.background = element_rect(fill = NA,
                                 color = "gray95",
                                 size = 10),
  plot.margin = unit(c(1, 1, 1, 1), "cm"),
) + theme_web_light
```


# Introduction and research question


```{r}
# density plot of activities

# add mean minutes infront of each activity name
density_plot_data <- atus_long %>% 
  group_by(description) %>% 
  mutate(Mean = round(mean(value), 0)) %>% 
  ungroup() %>% 
  mutate(label = paste0(round(Mean, 1), ' min: ', description))

# sort the label by the mean and move 'other' to bottom
label_order <- density_plot_data %>% 
  distinct(description, label, Mean) %>% 
  arrange(desc(Mean))
label_order <- label_order[c(1:10, 12:15, 11),]

# plot it
density_plot_data %>% 
  mutate(label = factor(label,
                        levels = label_order$label)) %>% 
  ggplot(aes(x = value, group = label, fill = label)) +
  geom_density(color = 'grey50', alpha = 0.4, adjust = 2) +
  scale_fill_discrete(name = 'Mean minutes: Activity') +
  scale_x_log10(labels = function(x) scales::comma(x, accuracy = 1)) +
  scale_y_continuous(labels = NULL) +
  labs(title = 'Weekend time use activities',
       subtitle = 'Non-zero values only',
       x = 'Minutes per day',
       y = NULL) +
  theme(legend.position = c(0.38, 0.65),
        legend.box.background = element_rect(color = 'white'),
        legend.background = element_rect(color = 'grey90'),
        legend.text = element_text(size = 7),
        legend.key.size = unit(0.4, "cm")) +
    guides(fill = guide_legend(ncol = 2))

save_plot(name = 'Weekend_time_use_activities')
save_plot(name = 'Weekend_time_use_activities', 
          plot = ggplot2::last_plot() + theme_web,
          type = 'svg',
          height = 5)
```


# Key findings


# Analysis

## Distance


```{r fig.height=4, fig.width=7}
# distance between categories
atus_long %>% 
  pivot_wider(values_from = value, names_from = description) %>% 
  select(-ID) %>% 
  as.matrix() %>% 
  t() %>% 
  dist() %>% 
  as.matrix() %>% 
  reshape::melt() %>% 
  ggplot(aes(x = reorder(X1, -value), y = reorder(X2, -value), fill = value)) +
  geom_tile() +
  scale_fill_gradient2(labels = scales::comma) +
  labs(title = "Euclidean distance between activities",
       x = NULL,
       y = NULL) +
  theme(axis.text.x = element_text(angle = 30, hjust = 1),
        legend.title = element_blank())

save_plot(name = 'Euclidean_distance_between_activities')
save_plot(name = 'Euclidean_distance_between_activities', 
          plot = ggplot2::last_plot() + theme_web + theme(axis.text = element_text(size = 7)),
          type = 'svg')
```

```{r}
# pivot wider and turn into matrix
atus_wide <- atus_long %>% 
  pivot_wider(values_from = value, names_from = description) %>% 
  select(-ID) %>% 
  as.matrix()
```

```{r}
# resample using survey weights
total_rows <- nrow(atus_wide)
sample_size <- 25000
rows_to_keep <- sample(1:total_rows, size = sample_size, prob = demographics$survey_weight, replace = TRUE)
IDs_kept <- atus_long %>% 
  pivot_wider(values_from = value, names_from = description) %>% 
  select(ID) %>% 
  .[rows_to_keep,]
atus_resampled <- atus_wide[rows_to_keep,]
```

## Clustering

```{r}
# distance matrix for features
dist_sc <- dist(atus_resampled, method = 'euclidean')

# ward (D2) linkage hier clustering
hcl_ward <- hclust(d = dist_sc, method = 'ward.D2')
# hcl_single <- hclust(d = dist_sc, method = 'single')
# hcl_centroid <- hclust(d = dist_sc, method = 'centroid')
```

```{r}
# convert cluster to dendrogram
dend <- as.dendrogram(hcl_ward)
dend <- cut(dend, h = 300)$upper # cut off bottom of dendogram for computation performance
ggd1 <- as.ggdend(dend)
```

```{r fig.height=3.7, fig.width=7}
# plot the dendrogram
ggplot(ggd1$segments) + 
  geom_segment(aes(x = x, y = y, xend = xend, yend = yend), color = 'grey50', lwd = 0.6, alpha = 0.7) +
  coord_cartesian(ylim = c(100, 45000), clip = 'off') +
  scale_x_continuous(labels = NULL) +
  scale_y_continuous(labels = NULL) +
  labs(title = 'Hierarchical clustering',
       subtitle= 'Ward (D2) linkage',
       x = NULL,
       y = NULL) +
  theme(axis.ticks = element_blank(),
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        legend.position = 'none')

save_plot(name = 'Hierarchical_cluster_bw', height = 2.7)
save_plot(name = 'Hierarchical_cluster_bw', 
          plot = ggplot2::last_plot() + theme_web,
          type = 'svg',
          height = 4,
          width = 7)
```

## Choosing number of clusters

```{r}
# trimmed, colored branches tree
hcl_k <- 6
dend <- as.dendrogram(hcl_ward) %>% set("branches_k_color", k = hcl_k) %>% set("labels_colors")
dend <- cut(dend, h = 300)$upper # cut off bottom of dendogram for computation performance
ggd1 <- as.ggdend(dend)
```

```{r}
# get labels from model
groupings <- cutree(hcl_ward, hcl_k)

# fix label switching problem
# get approx cluster size by counting line segments by color (proxy for cluster)
label_match <- ggd1$segments %>% 
  filter(col != '<NA>') %>% 
  group_by(col) %>% 
  filter(xend <= quantile(xend, 0.99),
         xend >= quantile(xend, 0.01)) %>% 
  summarize(x_min = min(xend),
            x_max = max(xend)) %>% 
  arrange(x_min) %>% 
    mutate(Approx_cluster_size = x_max - x_min,
           Cluster = 1:hcl_k) %>% 
  arrange(desc(Approx_cluster_size)) %>% 
  mutate(Actual_cluster = names(rev(sort(table(groupings))))) %>% 
  select(Dend_cluster = Cluster,
         Actual_cluster,
         col)

# replace groupings with similar vector but with switched labels
correct_clusters <- label_match$Dend_cluster[match(groupings, label_match$Actual_cluster)]
rm(groupings)
```

```{r}
# match brewer palette colors to cluster assignment
custom_colors <- colorspace::darken(RColorBrewer::brewer.pal(hcl_k, 'Spectral'), amount = 0.2)
label_match <- label_match %>% 
  arrange(Dend_cluster) %>% 
  mutate(brew_palette = custom_colors)

# replace colors with brewer colors
ggd1$segments$col <- label_match$brew_palette[match(ggd1$segments$col, label_match$col)]
```

```{r fig.height=4, fig.width=7}
# set dashed line for non-cluster segements
ggd1$segments$linetype <- 'solid'
ggd1$segments$linetype[which(is.na(ggd1$segments$col))] <- 'dashed'

# set connecting lines to grey
ggd1$segments$col[is.na(ggd1$segments$col)] <- 'grey50'

# set labels for below the plot
text_labels <- tribble(
  ~label, ~x, ~y,
  'Cluster 1', 1800, -2500,
  'Cluster 2', 4500, -2500,
  'Cluster 3', 8500, -2500,
  'Cluster 4', 13500, -2500,
  'Cluster 5', 16500, -2500,
  'Cluster 6', 21000, -2500
)

# plot the dendrogram
ggplot(ggd1$segments) + 
  geom_segment(aes(x = x, y = y, xend = xend, yend = yend), color = ggd1$segments$col,
               linetype = ggd1$segments$linetype, lwd = 0.6, alpha = 0.7) +
  geom_text(data = text_labels, aes(label = label, x = x, y = y), family = 'Helvetica') +
  coord_cartesian(ylim = c(100, 45000), clip = 'off') +
  scale_x_continuous(labels = NULL) +
  scale_y_continuous(labels = NULL) +
  labs(title = 'Hierarchical clustering',
       subtitle = 'Ward (D2) linkage: 6 cluster solution',
       x = NULL,
       y = NULL) +
  theme(axis.ticks = element_blank(),
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        legend.position = 'none',
        plot.margin = margin(t = 10, r = 10, b = 30, l = 10, unit = "pt"))

save_plot(name = 'Hierarchical_cluster_col', height = 3)
save_plot(name = 'Hierarchical_cluster_col', 
          plot = ggplot2::last_plot() + theme_web,
          type = 'svg',
          height = 4,
          width = 7)
```


# Breaking down the clusters

## Activities

```{r}
# activity densities lined up by cluster
atus_resampled %>% 
  as_tibble() %>% 
  bind_cols(group = as.character(correct_clusters)) %>%
  mutate(group = if_else(group == '1', 'Cluster 1', group),
         group = factor(group, levels = c("Cluster 1", 2:6))) %>% 
  pivot_longer(cols = -group) %>% 
  mutate(name = factor(name, levels = label_order$description)) %>% 
  ggplot(aes(x = value, group = name, fill = name)) +
  geom_density(alpha = 0.4, color = 'grey50', size = 0.5) +
  scale_fill_discrete(name = NULL) +
  scale_x_log10(limits = c(10, 1200)) +
  scale_y_continuous(labels = NULL) +
  facet_grid(group~., switch = 'y') +
  labs(title = 'Weekend activities split by cluster',
       x = 'Minutes per day',
       y = NULL)

save_plot(name = 'Weekend_activities_split_by_cluster')
save_plot(name = 'Weekend_activities_split_by_cluster', 
          plot = ggplot2::last_plot() + theme_web,
          type = 'svg',
          height = 5)
```


```{r}
# average minutes per cluster per activity
pop_avgs <- label_order %>% select(name = description, Mean_pop = Mean)
atus_resampled %>% 
  as_tibble() %>% 
  bind_cols(group = as.character(correct_clusters)) %>%
  mutate(group = if_else(group == '1', 'Cluster 1', group),
         group = factor(group, levels = c("Cluster 1", 2:6))) %>% 
  pivot_longer(cols = -group) %>% 
  mutate(name = factor(name, levels = label_order$description)) %>% 
  group_by(group, name) %>% 
  summarize(Mean_clus = mean(value)) %>% 
  left_join(pop_avgs) %>% 
  mutate(per_diff = Mean_clus / Mean_pop) %>% 
  arrange(group, desc(per_diff)) %>% 
  mutate(Mean_clus = round(Mean_clus, 2),
         per_diff = round(per_diff, 2)) %>% 
  View
rm(pop_avgs)
```

```{r}
# activites to show
activities_show <- c(
  'Caring For Household Member',
  'Household Activities',
  'Socializing, Relaxing, and Leisure',
  'Work')

# densities of activities by cluster
atus_resampled %>% 
  as_tibble() %>% 
  bind_cols(group = as.factor(correct_clusters)) %>%
  pivot_longer(cols = -group) %>% 
  filter(name %in% activities_show) %>% 
  ggplot(aes(x = value, group = group, fill = group)) +
  geom_density(color = 'grey50', alpha = 0.7) +
  scale_fill_brewer(palette = 'Spectral', name = 'Cluster') +
  scale_y_continuous(labels = NULL) +
  scale_x_log10(labels = function(x) scales::comma(x, accuracy = 1)) +
  facet_wrap(~name, nrow = 2, scales = 'fixed') +
  labs(title = 'Most distinct activities after accounting for cluster membership', 
       x = 'Minutes per day',
       y = NULL)

save_plot(name = 'Most_distinct_activities')
save_plot(name = 'Most_distinct_activities', 
          plot = ggplot2::last_plot() + theme_web,
          type = 'svg',
          height = 5)
```

## Who makes up each cluster? 

```{r}
population <- demographics %>% 
  right_join(bind_cols(IDs_kept)) %>%
  mutate(cluster = as.character(correct_clusters[match(ID, pull(IDs_kept))])) %>% 
  select(-survey_weight) %>% 
  rename(Age = age, Sex = sex, 'Household income' = HH_income, Married = married, 
         Race = race, Education = education)
```

```{r}
Age_plot <- population %>% 
  select(Age, cluster) %>%
  mutate(cluster = if_else(cluster == '1', 'Cluster 1', cluster),
         cluster = factor(cluster, levels = c("Cluster 1", 2:6))) %>% 
  pivot_longer(cols = c('Age')) %>%
  ggplot(aes(x = value, fill = cluster)) +
  geom_density(data = population %>% select(Age) %>% pivot_longer(cols = everything()),
               aes(x = value), alpha = 0.7, fill = 'grey40', color = 'grey50') +
  geom_density(alpha = 0.7, color = 'grey50') +
  scale_fill_brewer(palette = 'Spectral', name = NULL) +
  scale_y_continuous(labels = NULL) +
  facet_grid(cluster~name, scales = 'fixed',  switch = 'y') +
  labs(title = 'Clusters by distribution of age',
       subtitle = 'Grey distributions represent the population',
       x = 'Age',
       y = NULL) +
  theme(legend.position = 'none',
        strip.background = element_blank(),
        strip.text.x = element_blank(),
        plot.margin = unit(c(0.2, 0.2, .9, 0.2), units = 'cm')) +
  theme_web_light
```

```{r}
# barplot for income levels
income_levels <- c("0", "5,000", "7,500", "10,000", "12,500", "15,000", "20,000", "25,000", "30,000",  "35,000", "40,000", "50,000", "60,000", "75,000", "100,000", "150,000")

hline_data <- population %>% 
  mutate('Household income' = as.character(scales::comma(`Household income`))) %>%
  select('Household income') %>% 
  count(`Household income`) %>%
  na.omit() %>% 
  mutate(proportion = n / sum(n),
         `Household income` = factor(`Household income`, levels = income_levels))

income_plot <- population %>% 
  select('Household income', cluster) %>%
  mutate(cluster = if_else(cluster == '1', 'Cluster 1', cluster),
         cluster = factor(cluster, levels = c("Cluster 1", 2:6)),
         `Household income` = as.character(scales::comma(`Household income`)),
          `Household income` = factor(`Household income`, levels = income_levels)) %>%
  count(`Household income`, cluster) %>% 
  group_by(cluster) %>% 
  mutate(proportion = n / sum(n)) %>% 
  na.omit() %>% 
  ggplot(aes(x = `Household income`, y = proportion)) +
  geom_col(aes(fill = cluster), position = 'dodge', color = 'white') +
  geom_errorbar(data = hline_data, aes(ymin = proportion , ymax = proportion), color = 'grey50') +
  scale_fill_brewer(palette = 'Spectral', name = NULL) +
  scale_y_continuous(labels = NULL) +
  facet_grid(cluster~., scales = 'fixed') +
  labs(title = '...by household income',
       subtitle = 'Horizontal lines represent the population',
       x = 'Household income (USD/year)',
       y = NULL) +
  theme(legend.position = 'none',
        axis.text.x = element_text(angle = 40, hjust = 1),
        strip.background = element_blank(),
        strip.text.y = element_blank()) +
  theme_web_light
```

```{r fig.height=5, fig.width=7}
plot <- gridExtra::arrangeGrob(Age_plot, income_plot, ncol = 2)
save_plot(name = 'By_age_by_income', plot = plot, height = 3.6)
save_plot(name = 'By_age_by_income', 
          plot = plot,
          type = 'svg',
          height = 6)
rm(plot)
```

```{r}
# discrete
recoded_pop <- population %>% 
  select(Sex, Married, Education, has_child, cluster) %>% 
  mutate(Sex = recode(Sex, '1' = 'Male', '2' = 'Female'),
         Married = recode(Married, '0' = 'Not married', '1' = 'Married'),
         Child = recode(has_child, '0' = 'No children', '1' = 'Children in household'),
         cluster = if_else(cluster == '1', 'Cluster\n1', cluster),
         cluster = factor(cluster, levels = c("Cluster\n1", 2:6))) %>% 
  select(-has_child)
```

```{r}
# set custom colors
custom_colors <- rep(RColorBrewer::brewer.pal(hcl_k, 'Spectral'), each = 2)
# lighten every other color
custom_colors[((1:hcl_k %% 2)) == 1] <- colorspace::darken(custom_colors[((1:hcl_k %% 2)) == 1], amount = 0.2)
custom_colors[((1:hcl_k %% 2) + 1) == 1] <- colorspace::lighten(custom_colors[((1:hcl_k %% 2) + 1) == 1], amount = 0.4)
# set names to match the aes(fill)
names(custom_colors) <- paste0(rep(sort(unique(recoded_pop$cluster)), each = 2),
                               '-',
                               rep(c('Male', 'Female'), hcl_k))


sex_plot <- recoded_pop %>% 
  select(Sex, cluster) %>%
  group_by(cluster, Sex) %>% 
  summarize(Proportion = n()) %>% 
  group_by(cluster) %>% 
  mutate(Proportion = Proportion / sum(Proportion)) %>% 
  ungroup() %>% 
  mutate(fill = paste0(cluster, '-', Sex)) %>% 
  ggplot(aes(x = cluster, y = Proportion, group = fill, fill = fill, color = Sex)) +
  geom_col(position = 'stack', color = 'white') +
  geom_hline(data = recoded_pop[, 'Sex'] %>% count(Sex) %>% mutate(Proportion = n / sum(n)) %>% filter(Sex == 'Male'),
             aes(yintercept = Proportion),
             color = 'grey40', size = 0.8) +
  scale_fill_manual(values = custom_colors, name = NULL, guide = FALSE) +
  annotate(geom = 'text', x = 1, y = 0.3, angle = 90, family = 'Helvetica',
           label = 'Male', color = 'white', fontface = 'bold', size = 3) +
  annotate(geom = 'text', x = 1, y = 0.8, angle = 90, family = 'Helvetica',
           label = 'Female', color = 'grey30', fontface = 'bold', size = 3) +
  annotate(geom = 'text', x = 5, y = 0.53, family = 'Helvetica',
           label = 'Population mean', color = 'grey20', fontface = 'bold', size = 3.5) +
  scale_y_continuous(labels = NULL) +
  labs(title = 'Clusters split by sex', 
       x = NULL,
       y = 'Proportion of cluster population') +
  theme(legend.position = 'none',
        panel.grid.major.y = element_blank()) +
  theme_web_light
```

```{r}
# set names to match the aes(fill)
names(custom_colors) <- paste0(rep(sort(unique(recoded_pop$cluster)), each = 2),
                               '-',
                               rep(c('No children', 'Children in household'), hcl_k))

# bar plot by child status
child_plot <- recoded_pop %>% 
  select(Child, cluster) %>%
  group_by(cluster, Child) %>% 
  summarize(Proportion = n()) %>% 
  group_by(cluster) %>% 
  mutate(Proportion = Proportion / sum(Proportion)) %>% 
  ungroup() %>% 
  mutate(Child = paste0(cluster, '-', Child)) %>% 
  ggplot(aes(x = cluster, y = Proportion, group = Child, fill = Child)) +
  geom_col(position = 'stack', color = 'white') +
  geom_hline(data = recoded_pop[, 'Child'] %>% count(Child) %>% mutate(Proportion = n / sum(n)) %>% filter(Child == 'No children'),
             aes(yintercept = Proportion),
             color = 'grey40', size = 0.8) +
  scale_fill_manual(values = custom_colors, name = NULL, guide = FALSE) +
  annotate(geom = 'text', x = 1, y = 0.3, angle = 90, family = 'Helvetica',
           label = 'No children', color = 'white', fontface = 'bold', size = 3) +
  annotate(geom = 'text', x = 1, y = 0.8, angle = 90, family = 'Helvetica',
           label = 'Children in\n household', color = 'grey30', fontface = 'bold', size = 2.5) +
  scale_y_continuous(labels = NULL) +
  labs(title = '...by children in household', 
       x = NULL,
       y = NULL) +
  theme(legend.position = 'none',
        panel.grid.major.y = element_blank()) +
  theme_web_light
```

```{r}
# set names to match the aes(fill)
names(custom_colors) <- paste0(rep(sort(unique(recoded_pop$cluster)), each = 2),
                               '-',
                               rep(c('Not married', 'Married'), hcl_k))

# bar plot by marital status
marital_plot <- recoded_pop %>% 
  select(Married, cluster) %>%
  group_by(cluster, Married) %>% 
  summarize(Proportion = n()) %>% 
  group_by(cluster) %>% 
  mutate(Proportion = Proportion / sum(Proportion)) %>% 
  ungroup() %>% 
  mutate(Married = paste0(cluster, '-', Married)) %>% 
  ggplot(aes(x = cluster, y = Proportion, group = Married, fill = Married)) +
  geom_col(position = 'stack', color = 'white') +
  geom_hline(data = recoded_pop[, 'Married'] %>% count(Married) %>% mutate(Proportion = n / sum(n)) %>% filter(Married == 'Not married'),
             aes(yintercept = Proportion),
             color = 'grey40', size = 0.8) +
  scale_fill_manual(values = custom_colors, name = NULL, guide = FALSE) +
  annotate(geom = 'text', x = 1, y = 0.27, angle = 90, family = 'Helvetica',
           label = 'Not married', color = 'white', fontface = 'bold', size = 3) +
  annotate(geom = 'text', x = 1, y = 0.77, angle = 90, family = 'Helvetica',
           label = 'Married', color = 'grey30', fontface = 'bold', size = 3) +
  scale_y_continuous(labels = NULL) +
  labs(title = '...by marital status', 
       x = NULL,
       y = '') +
  theme(legend.position = 'none',
        panel.grid.major.y = element_blank()) +
  theme_web_light
```

```{r}
# attempt to color them to match the cluster colors
# set custom colors
custom_colors <- RColorBrewer::brewer.pal(hcl_k, 'Spectral')
custom_colors <- append(custom_colors, '#ababab')
# darken some and lighten others
custom_colors <- map(custom_colors, function(col) {
  col1 <- colorspace::darken(col, amount = 0.5)
  col2 <- colorspace::darken(col, amount = 0.3)
  col3 <- colorspace::darken(col, amount = 0.3)
  col4 <- col
  col5 <- colorspace::lighten(col, amount = 0.4)
  col6 <- colorspace::lighten(col, amount = 0.7)
  return(c(col1, col2, col3, col4, col5, col6))
}) %>% unlist()

# set names to match the aes(fill)
base_vector <- factor(c("Cluster\n1", 2:hcl_k, 'Population'), levels = c("Cluster\n1", 2:hcl_k, 'Population'))
names(custom_colors) <- paste0(rep(base_vector, each = 6),
                               '-',
                               rep(c('Did not graduate from HS', 'HS', 'Some college', 'Bachelors', 'Masters', 'Doctoral'), hcl_k))

# barplot(1:length(custom_colors), col = custom_colors)

# set labels for below the plot
text_labels <- tibble(
  label = c(
    'Did not graduate\nfrom HS',
    'HS',
    'Some college',
    'Bachelors',
    'Masters',
    'Doctoral'
  ),
  x = 7.6,
  y = c(0.08, 0.32, 0.59, 0.82, 0.92, 0.99),
  col = colorspace::darken(tail(custom_colors, 6), amount = 0.4))
        
# bar plot by education status
edu_status <- recoded_pop %>% 
  na.omit() %>% 
  select(Education, cluster) %>%
  group_by(cluster, Education) %>% 
  summarize(Proportion = n()) %>% 
  group_by(cluster) %>% 
  mutate(Proportion = Proportion / sum(Proportion)) %>% 
  ungroup()

edu_plot <- recoded_pop %>% 
  na.omit() %>% 
  select(Education) %>%
  count(Education) %>% 
  mutate(Proportion = n / sum(n),
         cluster = 'Population') %>% 
  ungroup() %>% 
  bind_rows(edu_status) %>% 
  mutate(Education = factor(Education, levels = rev(c('Did not graduate from HS', 'HS', 'Some college', 'Bachelors', 'Masters', 'Doctoral'))),
         cluster = factor(cluster, levels = c("Cluster\n1", 2:6, 'Population'))) %>%
  mutate(fill = paste0(cluster, '-', Education)) %>% 
  ggplot(aes(x = cluster, y = Proportion)) +
  geom_col(aes(group = Education, fill = fill), position = 'stack', color = 'white') +
  scale_fill_manual(values = custom_colors, name = NULL, guide = FALSE) +
  geom_text(data = text_labels, aes(label = label, x = x, y = y), 
            hjust = 0, color = text_labels$col, size = 2.5, family = 'Helvetica') +
  scale_y_continuous(labels = NULL) +
  coord_cartesian(xlim = c(1, 9), clip = 'off') +
  labs(title = '...by education', 
       x = NULL,
       y = NULL) +
  theme(legend.position = 'none',
        panel.grid.major.y = element_blank()) +
  theme_web_light
```

```{r fig.height=5, fig.width=7}
plot <- gridExtra::arrangeGrob(sex_plot, child_plot, marital_plot, edu_plot, ncol = 2)
save_plot(name = 'By_sex_child_marital_education', plot = plot, height = 4.6)
save_plot(name = 'By_sex_child_marital_education', 
          plot = plot,
          type = 'svg',
          height = 6)
rm(plot)
```

```{r}
# save cluster assingnments
IDs_kept %>%
  bind_cols(cluster = correct_clusters) %>% 
  write_csv('Analyses/25k_6_cluster_IDs.csv')
```


